### ISSUE TITLE
Extract assets from the game

### ISSUE THREAD

**Issue by emdu35** [RaenonX-PokemonTCGP/pokemon-tcgp-apk-dumper#2]
Hello,
I would like to extract the game assets (mainly the cards, in multiple languages), but the files are in an unknown binary format. Have you managed to extract them? If so, could you lend me some help?

Thanks.

**Comment by RaenonX** [comment]
@emdu35 Hey sorry I didn't notice you opened this up. If you still need help, DM me Discord @ raenonx :)
